server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    password: root
  redis:
    database: 1
    host: 121.4.122.91
    port: 6379
    password: root

############################################################
#
# mybatis 配置
#
############################################################

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl