server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://121.4.122.91:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    password: 15521040419