server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    password: 15521040419
  redis:
    database: 1
    host: 121.4.122.91
    port: 6379
    password: root

